export type PotteryClass = {
  id: string;
  slug: string;
  title: string;
  short_description: string;
  content: string;
  instructor_name: string;
  duration: string;
  class_date: string;
  class_time: string;
  price: number;
  total_seats: number;
  available_seats: number;
  thumbnail_url: string;
  gallery_images: string[];
  level: string;
  is_featured: boolean;
  is_published: boolean;
  created_at: string;
  updated_at: string;
};
